# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_details',
            name='Name',
        ),
        migrations.AddField(
            model_name='users_details',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='users_details',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
