# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180627_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
