# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_details',
            old_name='username',
            new_name='Email',
        ),
    ]
