# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180628_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_details',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='users_details',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
