# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
