# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180628_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_details',
        ),
    ]
