# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_users_details_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
